[WIP] ST-2195: Refactor NewLoginService() to a reusable library
linkernetworks/webservice pull request #4
Opened 2018-07-06 09:16 UTC by yarencheng

2018-07-09 03:08 UTC, c9s requested changes

2018-07-09 03:08 UTC, c9s commented on login/config/config.go
> +	MEMORY Type = "MEMORY"
Don't use full upper case for constant. Use `Memory`, `Mongo` ... etc

2018-07-09 03:08 UTC, c9s commented on login/entity/notification_preference.go
> +	WhenJobDelete  bool `json:"whenJobDelete" bson:"whenJobDelete"`
This should be not here.

2018-07-09 03:08 UTC, c9s commented on login/entity/session_response.go
> +}
Things are not stored in the db should not be in the entity package.

2018-07-09 03:08 UTC, c9s commented on login/entity/signIn_response.go
> +}
Things are not stored in the db should not be in the entity package.

2018-07-09 03:08 UTC, c9s commented on login/entity/user.go
> +	JobPriority           float64       `bson:"job_priority" json:"job_priority"`
This is not related. should be removed

2018-07-11 21:12 UTC, c9s approved these changes

2018-07-12 02:35 UTC, hwchiu approved these changes
LGTM

2018-07-12 02:35 UTC, merged